# Site
title:              smallSand
bio:                '我的个人博客'
description:        "我是smallsand,江汉大学2012级毕业生,就读于物理信息工程学院,目前在武汉从事软件开发工作，这是我的个人博客"
keywords   ：               smallsand,个人博客,江汉大学,2012级毕业生,Moon
reading_time:       true
words_per_minute:   200
logo:               http://o6n610sp1.bkt.clouddn.com/logo.png
background:         http://o6n610sp1.bkt.clouddn.com/placeholder-big.jpg
locale:             zh_CN
url:                http://smallSand.github.io
webResoure:         http://o6n610sp1.bkt.clouddn.com
# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            false
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   
uyan:     true

# Social
# if you don't have any of social below, comment the line.
#google_analytics: UA-78254230-1 
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:				1107050213@qq.com
#twitter:            username
#facebook:           username
github:             smallSand
#stackoverflow:      123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:           username
#xing:              username
#instagram:          username
#lastfm:             username
#tumblr:             username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:            username
#soundcloud:        username
weibo:              kznlsl
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
